package drools.rules

import rbs.wg.WorkoutGenerator.facts.WorkoutRequest;
import rbs.wg.WorkoutGenerator.facts.UserInformation;

global Random random;

rule "Previous workout was upper body, choose two lower body muscle groups"
    agenda-group "workout"
    when
        $user: UserInformation(upperBodyWorked == true) @Watch(!upperBodyWorked)
        $woPr: WorkoutProcessing()
    then
        System.out.println("----> Previous workout was upper body, choose two lower body muscle groups");
        modify($woPr) {
            setMuscleGroup(0, random.nextInt(4)+6),
            setMuscleGroup(1, random.nextInt(4)+6);
        }
end


rule "Previous workout was lower body, choose two upper body muscle groups"
    agenda-group "workout"
    when
        $user: UserInformation(upperBodyWorked == false) @Watch(!upperBodyWorked)
        $woPr: WorkoutProcessing()
    then
        System.out.println("----> Previous workout was lower body, choose two upper body muscle groups");
        modify($woPr) {
            setMuscleGroup(0, random.nextInt(6)),
            setMuscleGroup(1, random.nextInt(6));
        }
end