package drools.rules

import rbs.wg.WorkoutGenerator.model.AppUser;
import rbs.wg.WorkoutGenerator.model.UserLevel;
import rbs.wg.WorkoutGenerator.dto.WorkoutProcessingDto;
import java.util.Random;

global Random random;

rule "User is beginner, set workout intensity accordingly"
    when
        $user: AppUser(userLevel == UserLevel.BEGINNER)
        $woPr: WorkoutProcessingDto(numOfExercises == 0)
    then
        System.out.println("User is beginner, set workout intensity accordingly");
        modify($woPr) {
            setNumOfExercises(4 * $user.getNumOfExercisesFactor()),
            setWorkInterval(20 + $user.getWorkIntervalFactor()),
            setRestInterval($woPr.getWorkInterval()/2),
            setReps((random.nextInt(5)+4) * $user.getRepetitionFactor());
        }
end

rule "User is intermediate, set workout intensity accordingly"
    when
        $user: AppUser(userLevel == UserLevel.INTERMEDIATE)
        $woPr: WorkoutProcessingDto(numOfExercises == 0)
    then
        System.out.println("User is intermediate, set workout intensity accordingly");
        modify($woPr) {
            setNumOfExercises(5 * $user.getNumOfExercisesFactor()),
            setWorkInterval(30 + $user.getWorkIntervalFactor()),
            setRestInterval($woPr.getWorkInterval()/2),
            setReps((random.nextInt(5)+6) * $user.getRepetitionFactor());
        }
end


rule "User is advanced, set workout intensity accordingly"
    when
        $user: AppUser(userLevel == UserLevel.ADVANCED)
        $woPr: WorkoutProcessingDto(numOfExercises == 0)
    then
        System.out.println("User is advanced, set workout intensity accordingly");
        modify($woPr) {
            setNumOfExercises(6 * $user.getNumOfExercisesFactor()),
            setWorkInterval(40 + $user.getWorkIntervalFactor()),
            setRestInterval($woPr.getWorkInterval()/2),
            setReps((random.nextInt(5)+8) * $user.getRepetitionFactor());
        }
end

